### ISSUE TITLE
Task B array declaration

### ISSUE THREAD

**Issue by kuzznya** [SweetestRat/Algorithms-and-Data-Structures#1]
Нельзя объявлять статические массивы динамического размера
Для этого либо нужно использовать vector, либо через new

**Comment by s4xack** [comment]
Речь идет об этой строке:
>  int matrix[matrixsize][matrixsize];

**Comment by SweetestRat** [comment]
Окей, спосебаа, а почему так?

**Comment by SweetestRat** [comment]
Лан, погуглю

**Comment by s4xack** [comment]
@SweetestRat 
https://www.geeksforgeeks.org/variable-length-arrays-in-c-and-c/
